# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default=123, max_length=32),
            preserve_default=False,
        ),
    ]
